adj = input("Enter an adjective: ")
noun = input("Enter a noun: ")
verb = input("Enter a verb: ")
adj2 = input("Enter an adjective: ")
adj3 = input("Enter an adjective: ")

print(f"Today i went to a {adj} zoo.")
print(f"In the exhibit, I saw {noun}.")
print(f"{noun} was {adj2} and {verb}ing.")
print(f"I was {adj3}.")
